"use strict";
const DEMO_PRODUCTS=[
 {id:"demo-pocket",type:"hand",title:"Briesje Pocket",subtitle:"Handventilator · demonstratie",price:16.95,description:"Compact prototype; eigenschappen zijn niet aan een leverancier ontleend.",available:true,color:"#e8efd3",accent:"#ef7d62"},
 {id:"demo-fold",type:"desk",title:"Briesje Fold",subtitle:"Opvouwbaar · demonstratie",price:21.95,description:"Fictief concept met verstelbare standaard en USB-aansluiting.",available:true,color:"#dceee5",accent:"#f4ca66"},
 {id:"demo-trail",type:"outdoor",title:"Briesje Trail",subtitle:"Campingmodel · demonstratie",price:36.95,description:"Demo-concept; accuduur en lamp zijn niet getest.",available:true,color:"#f6e7db",accent:"#61a88a"},
 {id:"source-a",type:"source",title:"Bronproduct A",subtitle:"Leveranciersreferentie · geblokkeerd",price:null,description:"Geen gevalideerde prijs, voorraad, levering of veiligheidsdocumentatie.",available:false,color:"#edf0ec",accent:"#9aa9a1"},
 {id:"source-b",type:"source",title:"Bronproduct B",subtitle:"Leveranciersreferentie · geblokkeerd",price:null,description:"Geen gevalideerde prijs, voorraad, levering of veiligheidsdocumentatie.",available:false,color:"#edf0ec",accent:"#9aa9a1"},
 {id:"demo-neck",type:"outdoor",title:"Briesje Nek",subtitle:"Nekventilator · demonstratie",price:24.95,description:"Fictief concept; draagcomfort en veiligheid zijn niet beoordeeld.",available:true,color:"#e5e2f3",accent:"#ef7d62"}
];
let PRODUCTS=DEMO_PRODUCTS;
const money=new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"});
const state={filter:"all",cart:read("briesje-cart",{}),account:null,supabase:null,backend:"demo"};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(){localStorage.setItem("briesje-cart",JSON.stringify(state.cart))}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function fan(){return '<div class="mini-fan" aria-hidden="true"><b></b><b></b><b></b></div>'}
function configured(){const c=window.BRIESJE_CONFIG||{};return /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(c.supabaseUrl||"")&&typeof c.supabaseAnonKey==="string"&&c.supabaseAnonKey.length>20&&!/PUBLIC_ANON|PLACEHOLDER/i.test(c.supabaseAnonKey)}
function script(src){return new Promise((ok,no)=>{const s=document.createElement("script");s.src=src;s.crossOrigin="anonymous";s.onload=ok;s.onerror=no;document.head.append(s)})}
async function initBackend(){if(!configured())return;try{await script("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.49.8/dist/umd/supabase.min.js");const c=window.BRIESJE_CONFIG;state.supabase=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey,{auth:{persistSession:true,detectSessionInUrl:true}});const {data:{session}}=await state.supabase.auth.getSession();state.account=session?.user||null;state.supabase.auth.onAuthStateChange((_e,s)=>{state.account=s?.user||null;if($("#account-dialog").open)renderAccount()});await loadCatalog();state.backend="supabase";$("#catalog-note").textContent="Dit zijn uitsluitend server-goedgekeurde artikelen. Prijs en beschikbaarheid worden bij afrekenen opnieuw gecontroleerd.";$("#cart-status").textContent="Definitieve prijs en beschikbaarheid worden veilig op de server gecontroleerd.";renderProducts();renderCart()}catch(e){console.warn("Veilige terugval naar conceptcatalogus",e);state.supabase=null;state.backend="demo";PRODUCTS=DEMO_PRODUCTS;toast("De actuele collectie is niet bereikbaar; conceptweergave actief.")}}
async function loadCatalog(){const c=window.BRIESJE_CONFIG,{data,error}=await state.supabase.from(c.catalogView||"public_catalog").select("id,title,subtitle,description,category,sale_price_minor,currency,status").eq("status","approved");if(error)throw error;if(!data?.length)throw Error("Lege catalogus");PRODUCTS=data.map((r,i)=>({id:String(r.id),type:["hand","desk","outdoor"].includes(r.category)?r.category:"all",title:String(r.title||"Product"),subtitle:String(r.subtitle||"Goedgekeurd product"),description:String(r.description||""),price:Number.isInteger(r.sale_price_minor)&&r.sale_price_minor>0&&r.currency==="EUR"?r.sale_price_minor/100:null,available:Number.isInteger(r.sale_price_minor)&&r.sale_price_minor>0&&r.currency==="EUR",color:["#e8efd3","#dceee5","#f6e7db"][i%3],accent:"#ef7d62",live:true})).filter(p=>p.available);if(!PRODUCTS.length)throw Error("Geen veilig geprijsde regels")}
function product(id){return PRODUCTS.find(p=>p.id===id)}
function renderProducts(){const ps=PRODUCTS.filter(p=>state.filter==="all"||p.type===state.filter);$("#product-grid").innerHTML=ps.map(p=>`<article class="product-card"><div class="product-art" style="--card-bg:${p.color};--accent:${p.accent}"><span class="demo-label">${p.live?"Beschikbaar":p.type==="source"?"Bronreferentie":"Concept"}</span>${!p.available?'<span class="status-label">Niet te koop</span>':""}${fan()}</div><div class="product-body"><span class="product-type">${esc(p.subtitle)}</span><div class="product-title-row"><h3>${esc(p.title)}</h3><span class="product-price">${p.price===null?"Prijs onbekend":money.format(p.price)}</span></div><p>${esc(p.description)}</p><div class="product-actions"><button class="button button-secondary" data-detail="${esc(p.id)}">Bekijk</button><button class="button button-primary" data-add="${esc(p.id)}" ${p.available?"":"disabled"}>${p.available?(p.live?"In winkelmand":"Bewaar concept"):"Geblokkeerd"}</button></div></div></article>`).join("")}
function showDetail(id){const p=product(id);if(!p)return;$("#product-detail").innerHTML=`<button class="dialog-close" data-close aria-label="Sluiten">×</button><div class="detail-layout"><div class="detail-art" style="--accent:${p.accent}">${fan()}</div><div><p class="eyebrow">${p.live?"Catalogusproduct":p.type==="source"?"Bronreferentie":"Demoproduct"}</p><h2 id="product-title">${esc(p.title)}</h2><strong>${p.price===null?"Geen verkoopprijs":money.format(p.price)+(p.live?"":" · fictief")}</strong><p>${esc(p.description)}</p><p class="account-note">${p.live?"Prijs en beschikbaarheid worden bij checkout opnieuw op de server gecontroleerd.":"Dit is geen echt productaanbod."}</p>${p.itemId?`<div class="detail-meta"><strong>AliExpress item-ID</strong><br>${p.itemId}<br><strong>Voorkeurs-SKU</strong><br>${p.skuId}</div>`:""}<button class="button button-primary" data-add="${esc(p.id)}" ${p.available?"":"disabled"}>${p.available?"Voeg toe":"Fail-closed geblokkeerd"}</button></div></div>`;$("#product-dialog").showModal()}
function add(id){const p=product(id);if(!p?.available)return toast("Dit product blijft geblokkeerd.");state.cart[id]=Math.min((state.cart[id]||0)+1,5);save();renderCart();toast(`${p.title} staat in je winkelmand.`)}
function lines(){return Object.entries(state.cart).map(([id,quantity])=>({p:product(id),quantity})).filter(x=>x.p?.available&&x.quantity>0)}
function renderCart(){const ls=lines(),n=ls.reduce((s,x)=>s+x.quantity,0),total=ls.reduce((s,x)=>s+x.p.price*x.quantity,0);$("#cart-count").textContent=n;$("#cart-open").setAttribute("aria-label",`Winkelmand openen, ${n} artikelen`);$("#cart-total").textContent=money.format(total);$("#cart-items").innerHTML=ls.length?ls.map(({p,quantity})=>`<article class="cart-line"><div class="cart-thumb">⌁</div><div><h3>${esc(p.title)}</h3><p>${money.format(p.price)}${p.live?"":" · demo"}</p><div class="qty"><button data-qty="${esc(p.id)}" data-delta="-1">−</button><span>${quantity}</span><button data-qty="${esc(p.id)}" data-delta="1">+</button></div></div><button class="remove" data-remove="${esc(p.id)}">Verwijder</button></article>`).join(""):'<div class="empty-cart"><p>Je winkelmand is leeg.</p><a href="#producten" id="shop-link">Bekijk de collectie</a></div>';$("#checkout").disabled=!ls.length}
function qty(id,d){state.cart[id]=Math.max(0,Math.min(5,(state.cart[id]||0)+d));if(!state.cart[id])delete state.cart[id];save();renderCart()}
function openCart(){$("#cart-panel").classList.add("open");$("#cart-panel").setAttribute("aria-hidden","false");$("#scrim").hidden=false;document.body.style.overflow="hidden"}
function closeCart(){$("#cart-panel").classList.remove("open");$("#cart-panel").setAttribute("aria-hidden","true");$("#scrim").hidden=true;document.body.style.overflow=""}
function renderAccount(){if(state.supabase){$("#account-content").innerHTML=state.account?`<p>Ingelogd als <strong>${esc(state.account.email||"account")}</strong>.</p><p class="account-note">Je bestelgeschiedenis verschijnt hier zodra bestellen is geopend.</p><button class="button button-secondary" id="logout">Uitloggen</button>`:'<p>Ontvang een veilige inloglink per e-mail.</p><form id="magic-login"><label for="email">E-mailadres</label><input id="email" name="email" type="email" autocomplete="email" required><button class="button button-primary">Stuur inloglink</button></form><p class="account-note">De link brengt je veilig terug naar deze pagina.</p>';return}$("#account-content").innerHTML='<p>Mijn Briesje is nog niet geopend.</p><p class="account-note">Zodra de beveiligde accountomgeving is gekoppeld, kun je hier met een magic link inloggen. We vragen nu geen persoonsgegevens.</p>'}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2600)}
function info(title,body){$("#info-title").textContent=title;$("#info-content").innerHTML=`<p>${body}</p>`;$("#info-dialog").showModal()}
async function checkout(){const ls=lines();closeCart();if(state.backend!=="supabase"||!state.supabase||ls.some(x=>!x.p.live))return info("Afrekenen nog niet beschikbaar","Er is niets betaald. Briesje opent afrekenen pas voor server-goedgekeurde producten.");if(!state.account)return info("Log eerst in","Voor checkout is een account met geldige sessie vereist.");try{const attempt=crypto.randomUUID();const {data,error}=await state.supabase.functions.invoke(window.BRIESJE_CONFIG.checkoutFunction||"create-checkout-session",{body:{items:ls.map(x=>({variantId:x.p.id,quantity:x.quantity})),checkoutAttempt:attempt,shippingCountry:"NL"}});if(error)throw error;const url=data?.checkoutUrl;if(typeof url!=="string"||!/^https:\/\/checkout\.stripe\.com\//.test(url))throw Error("Ongeldige checkout-URL");location.assign(url)}catch(e){console.warn("Checkout veilig gestopt",e);info("Checkout niet gestart","De server kon prijs of beschikbaarheid niet veilig bevestigen. Er is niets betaald.")}}
document.addEventListener("click",async e=>{const d=e.target.closest("[data-detail]"),a=e.target.closest("[data-add]"),f=e.target.closest("[data-filter]"),c=e.target.closest("[data-close]"),q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]"),i=e.target.closest("[data-info]");if(d)showDetail(d.dataset.detail);if(a&&!a.disabled)add(a.dataset.add);if(f){state.filter=f.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle("active",b===f));renderProducts()}if(c)c.closest("dialog").close();if(q)qty(q.dataset.qty,Number(q.dataset.delta));if(r){delete state.cart[r.dataset.remove];save();renderCart()}if(i){const m={contact:["Contact nog niet actief","Briesje heeft nog geen operationeel supportadres."],privacy:["Privacy","In demomodus blijft de winkelmand lokaal. Bij Supabase-login verwerkt Supabase het e-mailadres."],voorwaarden:["Voorwaarden nog niet vastgesteld","Juridische voorwaarden moeten vóór verkoop worden gecontroleerd."]}[i.dataset.info];info(...m)}if(e.target.id==="shop-link")closeCart();if(e.target.id==="logout"&&state.supabase){await state.supabase.auth.signOut();renderAccount()}});
document.addEventListener("submit",async e=>{if(e.target.id!=="magic-login")return;e.preventDefault();const email=new FormData(e.target).get("email").trim();const button=$("button",e.target);button.disabled=true;const {error}=await state.supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});button.disabled=false;if(error)return toast("Inloglink kon niet worden verstuurd.");e.target.reset();toast("Controleer je e-mail voor de inloglink.")});
$("#cart-open").onclick=openCart;$("#cart-close").onclick=closeCart;$("#scrim").onclick=closeCart;$("#account-open").onclick=()=>{renderAccount();$("#account-dialog").showModal()};$("#checkout").onclick=checkout;document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("#cart-panel").classList.contains("open"))closeCart()});$("#year").textContent=new Date().getFullYear();renderProducts();renderCart();initBackend();
